### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by rijobro** [spotify/spotify-web-playback-sdk-example#4]
I haven't changed any files, I simply added the .env file with the credentials as per the readme. After authentication, the following text is displayed on screen:

> INVALID_CLIENT: Invalid redirect URI

**Comment by chettriyuvraj** [comment]
The redirect_uri used in /server/index.js must match the redirect_uri on your Spotify App (@ developers.spotify.com). Go to 'Edit Settings' on your Spotify App and set redirect_uri to 'http://localhost:3000/auth/callback'. I think you should be good.

**Comment by rijobro** [comment]
Correct, apologies about that!
